/*
 * generated by Xtext 2.26.0
 */
package security.xtext.bmpn.simple.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import security.xtext.bmpn.simple.ui.internal.SimpleActivator;

public class BPSecDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SimpleActivator.getInstance().getInjector("security.xtext.bmpn.simple.BPSecDsl");
	}

}
