/*
 * generated by Xtext 2.26.0
 */
package security.xtext.bmpn.simple.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import security.xtext.bmpn.simple.ui.internal.SimpleActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BPSecDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SimpleActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SimpleActivator activator = SimpleActivator.getInstance();
		return activator != null ? activator.getInjector(SimpleActivator.SECURITY_XTEXT_BMPN_SIMPLE_BPSECDSL) : null;
	}

}
