/**
 * generated by Xtext 2.26.0
 */
package security.xtext.bmpn.simple.bPSecDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see security.xtext.bmpn.simple.bPSecDsl.BPSecDslFactory
 * @model kind="package"
 * @generated
 */
public interface BPSecDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "bPSecDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.security/bmpn/simple/BPSecDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "bPSecDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BPSecDslPackage eINSTANCE = security.xtext.bmpn.simple.bPSecDsl.impl.BPSecDslPackageImpl.init();

  /**
   * The meta object id for the '{@link security.xtext.bmpn.simple.bPSecDsl.impl.PolicyImpl <em>Policy</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see security.xtext.bmpn.simple.bPSecDsl.impl.PolicyImpl
   * @see security.xtext.bmpn.simple.bPSecDsl.impl.BPSecDslPackageImpl#getPolicy()
   * @generated
   */
  int POLICY = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLICY__NAME = 0;

  /**
   * The feature id for the '<em><b>Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLICY__DECLARATIONS = 1;

  /**
   * The number of structural features of the '<em>Policy</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLICY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link security.xtext.bmpn.simple.bPSecDsl.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see security.xtext.bmpn.simple.bPSecDsl.impl.DeclarationImpl
   * @see security.xtext.bmpn.simple.bPSecDsl.impl.BPSecDslPackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATION = 1;

  /**
   * The feature id for the '<em><b>Processes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__PROCESSES = 0;

  /**
   * The feature id for the '<em><b>Users</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__USERS = 1;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link security.xtext.bmpn.simple.bPSecDsl.impl.ProcessImpl <em>Process</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see security.xtext.bmpn.simple.bPSecDsl.impl.ProcessImpl
   * @see security.xtext.bmpn.simple.bPSecDsl.impl.BPSecDslPackageImpl#getProcess()
   * @generated
   */
  int PROCESS = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__NAME = 0;

  /**
   * The feature id for the '<em><b>Ref Process</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__REF_PROCESS = 1;

  /**
   * The feature id for the '<em><b>Tasks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__TASKS = 2;

  /**
   * The number of structural features of the '<em>Process</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link security.xtext.bmpn.simple.bPSecDsl.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see security.xtext.bmpn.simple.bPSecDsl.impl.TaskImpl
   * @see security.xtext.bmpn.simple.bPSecDsl.impl.BPSecDslPackageImpl#getTask()
   * @generated
   */
  int TASK = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__NAME = 0;

  /**
   * The feature id for the '<em><b>Ref Task</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__REF_TASK = 1;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link security.xtext.bmpn.simple.bPSecDsl.impl.UserImpl <em>User</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see security.xtext.bmpn.simple.bPSecDsl.impl.UserImpl
   * @see security.xtext.bmpn.simple.bPSecDsl.impl.BPSecDslPackageImpl#getUser()
   * @generated
   */
  int USER = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER__NAME = 0;

  /**
   * The number of structural features of the '<em>User</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link security.xtext.bmpn.simple.bPSecDsl.Policy <em>Policy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Policy</em>'.
   * @see security.xtext.bmpn.simple.bPSecDsl.Policy
   * @generated
   */
  EClass getPolicy();

  /**
   * Returns the meta object for the attribute '{@link security.xtext.bmpn.simple.bPSecDsl.Policy#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see security.xtext.bmpn.simple.bPSecDsl.Policy#getName()
   * @see #getPolicy()
   * @generated
   */
  EAttribute getPolicy_Name();

  /**
   * Returns the meta object for the containment reference list '{@link security.xtext.bmpn.simple.bPSecDsl.Policy#getDeclarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declarations</em>'.
   * @see security.xtext.bmpn.simple.bPSecDsl.Policy#getDeclarations()
   * @see #getPolicy()
   * @generated
   */
  EReference getPolicy_Declarations();

  /**
   * Returns the meta object for class '{@link security.xtext.bmpn.simple.bPSecDsl.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see security.xtext.bmpn.simple.bPSecDsl.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for the containment reference list '{@link security.xtext.bmpn.simple.bPSecDsl.Declaration#getProcesses <em>Processes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Processes</em>'.
   * @see security.xtext.bmpn.simple.bPSecDsl.Declaration#getProcesses()
   * @see #getDeclaration()
   * @generated
   */
  EReference getDeclaration_Processes();

  /**
   * Returns the meta object for the containment reference list '{@link security.xtext.bmpn.simple.bPSecDsl.Declaration#getUsers <em>Users</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Users</em>'.
   * @see security.xtext.bmpn.simple.bPSecDsl.Declaration#getUsers()
   * @see #getDeclaration()
   * @generated
   */
  EReference getDeclaration_Users();

  /**
   * Returns the meta object for class '{@link security.xtext.bmpn.simple.bPSecDsl.Process <em>Process</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Process</em>'.
   * @see security.xtext.bmpn.simple.bPSecDsl.Process
   * @generated
   */
  EClass getProcess();

  /**
   * Returns the meta object for the attribute '{@link security.xtext.bmpn.simple.bPSecDsl.Process#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see security.xtext.bmpn.simple.bPSecDsl.Process#getName()
   * @see #getProcess()
   * @generated
   */
  EAttribute getProcess_Name();

  /**
   * Returns the meta object for the reference '{@link security.xtext.bmpn.simple.bPSecDsl.Process#getRefProcess <em>Ref Process</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref Process</em>'.
   * @see security.xtext.bmpn.simple.bPSecDsl.Process#getRefProcess()
   * @see #getProcess()
   * @generated
   */
  EReference getProcess_RefProcess();

  /**
   * Returns the meta object for the containment reference list '{@link security.xtext.bmpn.simple.bPSecDsl.Process#getTasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tasks</em>'.
   * @see security.xtext.bmpn.simple.bPSecDsl.Process#getTasks()
   * @see #getProcess()
   * @generated
   */
  EReference getProcess_Tasks();

  /**
   * Returns the meta object for class '{@link security.xtext.bmpn.simple.bPSecDsl.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see security.xtext.bmpn.simple.bPSecDsl.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the attribute '{@link security.xtext.bmpn.simple.bPSecDsl.Task#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see security.xtext.bmpn.simple.bPSecDsl.Task#getName()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Name();

  /**
   * Returns the meta object for the reference '{@link security.xtext.bmpn.simple.bPSecDsl.Task#getRefTask <em>Ref Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref Task</em>'.
   * @see security.xtext.bmpn.simple.bPSecDsl.Task#getRefTask()
   * @see #getTask()
   * @generated
   */
  EReference getTask_RefTask();

  /**
   * Returns the meta object for class '{@link security.xtext.bmpn.simple.bPSecDsl.User <em>User</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User</em>'.
   * @see security.xtext.bmpn.simple.bPSecDsl.User
   * @generated
   */
  EClass getUser();

  /**
   * Returns the meta object for the attribute '{@link security.xtext.bmpn.simple.bPSecDsl.User#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see security.xtext.bmpn.simple.bPSecDsl.User#getName()
   * @see #getUser()
   * @generated
   */
  EAttribute getUser_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BPSecDslFactory getBPSecDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link security.xtext.bmpn.simple.bPSecDsl.impl.PolicyImpl <em>Policy</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see security.xtext.bmpn.simple.bPSecDsl.impl.PolicyImpl
     * @see security.xtext.bmpn.simple.bPSecDsl.impl.BPSecDslPackageImpl#getPolicy()
     * @generated
     */
    EClass POLICY = eINSTANCE.getPolicy();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POLICY__NAME = eINSTANCE.getPolicy_Name();

    /**
     * The meta object literal for the '<em><b>Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POLICY__DECLARATIONS = eINSTANCE.getPolicy_Declarations();

    /**
     * The meta object literal for the '{@link security.xtext.bmpn.simple.bPSecDsl.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see security.xtext.bmpn.simple.bPSecDsl.impl.DeclarationImpl
     * @see security.xtext.bmpn.simple.bPSecDsl.impl.BPSecDslPackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATION = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '<em><b>Processes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARATION__PROCESSES = eINSTANCE.getDeclaration_Processes();

    /**
     * The meta object literal for the '<em><b>Users</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARATION__USERS = eINSTANCE.getDeclaration_Users();

    /**
     * The meta object literal for the '{@link security.xtext.bmpn.simple.bPSecDsl.impl.ProcessImpl <em>Process</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see security.xtext.bmpn.simple.bPSecDsl.impl.ProcessImpl
     * @see security.xtext.bmpn.simple.bPSecDsl.impl.BPSecDslPackageImpl#getProcess()
     * @generated
     */
    EClass PROCESS = eINSTANCE.getProcess();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESS__NAME = eINSTANCE.getProcess_Name();

    /**
     * The meta object literal for the '<em><b>Ref Process</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESS__REF_PROCESS = eINSTANCE.getProcess_RefProcess();

    /**
     * The meta object literal for the '<em><b>Tasks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESS__TASKS = eINSTANCE.getProcess_Tasks();

    /**
     * The meta object literal for the '{@link security.xtext.bmpn.simple.bPSecDsl.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see security.xtext.bmpn.simple.bPSecDsl.impl.TaskImpl
     * @see security.xtext.bmpn.simple.bPSecDsl.impl.BPSecDslPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__NAME = eINSTANCE.getTask_Name();

    /**
     * The meta object literal for the '<em><b>Ref Task</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__REF_TASK = eINSTANCE.getTask_RefTask();

    /**
     * The meta object literal for the '{@link security.xtext.bmpn.simple.bPSecDsl.impl.UserImpl <em>User</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see security.xtext.bmpn.simple.bPSecDsl.impl.UserImpl
     * @see security.xtext.bmpn.simple.bPSecDsl.impl.BPSecDslPackageImpl#getUser()
     * @generated
     */
    EClass USER = eINSTANCE.getUser();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER__NAME = eINSTANCE.getUser_Name();

  }

} //BPSecDslPackage
