/**
 * generated by Xtext 2.26.0
 */
package security.xtext.bmpn.simple.bPSecDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link security.xtext.bmpn.simple.bPSecDsl.Declaration#getProcesses <em>Processes</em>}</li>
 *   <li>{@link security.xtext.bmpn.simple.bPSecDsl.Declaration#getUsers <em>Users</em>}</li>
 * </ul>
 *
 * @see security.xtext.bmpn.simple.bPSecDsl.BPSecDslPackage#getDeclaration()
 * @model
 * @generated
 */
public interface Declaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Processes</b></em>' containment reference list.
   * The list contents are of type {@link security.xtext.bmpn.simple.bPSecDsl.Process}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Processes</em>' containment reference list.
   * @see security.xtext.bmpn.simple.bPSecDsl.BPSecDslPackage#getDeclaration_Processes()
   * @model containment="true"
   * @generated
   */
  EList<security.xtext.bmpn.simple.bPSecDsl.Process> getProcesses();

  /**
   * Returns the value of the '<em><b>Users</b></em>' containment reference list.
   * The list contents are of type {@link security.xtext.bmpn.simple.bPSecDsl.User}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Users</em>' containment reference list.
   * @see security.xtext.bmpn.simple.bPSecDsl.BPSecDslPackage#getDeclaration_Users()
   * @model containment="true"
   * @generated
   */
  EList<User> getUsers();

} // Declaration
