/**
 * generated by Xtext 2.26.0
 */
package security.xtext.bmpn.simple.bPSecDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link security.xtext.bmpn.simple.bPSecDsl.Process#getName <em>Name</em>}</li>
 *   <li>{@link security.xtext.bmpn.simple.bPSecDsl.Process#getRefProcess <em>Ref Process</em>}</li>
 *   <li>{@link security.xtext.bmpn.simple.bPSecDsl.Process#getTasks <em>Tasks</em>}</li>
 * </ul>
 *
 * @see security.xtext.bmpn.simple.bPSecDsl.BPSecDslPackage#getProcess()
 * @model
 * @generated
 */
public interface Process extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see security.xtext.bmpn.simple.bPSecDsl.BPSecDslPackage#getProcess_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link security.xtext.bmpn.simple.bPSecDsl.Process#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Ref Process</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref Process</em>' reference.
   * @see #setRefProcess(org.eclipse.bpmn2.Process)
   * @see security.xtext.bmpn.simple.bPSecDsl.BPSecDslPackage#getProcess_RefProcess()
   * @model
   * @generated
   */
  org.eclipse.bpmn2.Process getRefProcess();

  /**
   * Sets the value of the '{@link security.xtext.bmpn.simple.bPSecDsl.Process#getRefProcess <em>Ref Process</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref Process</em>' reference.
   * @see #getRefProcess()
   * @generated
   */
  void setRefProcess(org.eclipse.bpmn2.Process value);

  /**
   * Returns the value of the '<em><b>Tasks</b></em>' containment reference list.
   * The list contents are of type {@link security.xtext.bmpn.simple.bPSecDsl.Task}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tasks</em>' containment reference list.
   * @see security.xtext.bmpn.simple.bPSecDsl.BPSecDslPackage#getProcess_Tasks()
   * @model containment="true"
   * @generated
   */
  EList<Task> getTasks();

} // Process
