/**
 * generated by Xtext 2.26.0
 */
package security.xtext.bmpn.simple.bPSecDsl;

import org.eclipse.bpmn2.Activity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link security.xtext.bmpn.simple.bPSecDsl.Task#getName <em>Name</em>}</li>
 *   <li>{@link security.xtext.bmpn.simple.bPSecDsl.Task#getRefTask <em>Ref Task</em>}</li>
 * </ul>
 *
 * @see security.xtext.bmpn.simple.bPSecDsl.BPSecDslPackage#getTask()
 * @model
 * @generated
 */
public interface Task extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see security.xtext.bmpn.simple.bPSecDsl.BPSecDslPackage#getTask_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link security.xtext.bmpn.simple.bPSecDsl.Task#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Ref Task</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref Task</em>' reference.
   * @see #setRefTask(Activity)
   * @see security.xtext.bmpn.simple.bPSecDsl.BPSecDslPackage#getTask_RefTask()
   * @model
   * @generated
   */
  Activity getRefTask();

  /**
   * Sets the value of the '{@link security.xtext.bmpn.simple.bPSecDsl.Task#getRefTask <em>Ref Task</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref Task</em>' reference.
   * @see #getRefTask()
   * @generated
   */
  void setRefTask(Activity value);

} // Task
