/*
 * generated by Xtext 2.26.0
 */
package security.xtext.bmpn.simple.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BPSecDslUiModule extends AbstractBPSecDslUiModule {

	public BPSecDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
