/*
 * generated by Xtext 2.26.0
 */
package security.xtext.bmpn.simple.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBPSecDslScopeProvider extends DelegatingScopeProvider {
}
