/*
 * generated by Xtext 2.26.0
 */
package security.xtext.bmpn.simple.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import security.xtext.bmpn.simple.parser.antlr.internal.InternalBPSecDslParser;
import security.xtext.bmpn.simple.services.BPSecDslGrammarAccess;

public class BPSecDslParser extends AbstractAntlrParser {

	@Inject
	private BPSecDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBPSecDslParser createParser(XtextTokenStream stream) {
		return new InternalBPSecDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Policy";
	}

	public BPSecDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BPSecDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
