/*
 * generated by Xtext 2.26.0
 */
package security.xtext.bmpn.simple.ide;


/**
 * Use this class to register ide components.
 */
public class BPSecDslIdeModule extends AbstractBPSecDslIdeModule {
}
