/*
 * generated by Xtext 2.26.0
 */
package security.xtext.bmpn.simple.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import security.xtext.bmpn.simple.BPSecDslRuntimeModule;
import security.xtext.bmpn.simple.BPSecDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BPSecDslIdeSetup extends BPSecDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BPSecDslRuntimeModule(), new BPSecDslIdeModule()));
	}
	
}
